### ISSUE TITLE
Request: Allow make target specification in ./build* scripts

### ISSUE THREAD

**Issue by andrewzigerelli** [cirosantilli/linux-kernel-module-cheat#113]
Hi Ciro,

I see that the make is hardcoded (I'm only looking at build-qemu specifically). I wanted to run "make check" to run the qemu tests.

I'm not sure if this better handled where "make" is currently hardcoded, or maybe in common.py?

I don't fully understand the "build architecture", or else I would just do it and make a pull req..

This is obviously low priority, because I can easily go to the correct folder in out/ and run it myself, but maybe it's a nice feature to add?

Feel free to close if you disagree, again, it's not a huge deal.

**Comment by cirosantilli** [comment]
Andrew, thanks for the suggestion, give a try to see if it is working :-)
