### ISSUE TITLE
gdb requires nokaslr flag in ./run to get symbols

### ISSUE THREAD

**Issue by dakami** [cirosantilli/linux-kernel-module-cheat#12]
What it says on the tin

**Comment by cirosantilli** [comment]
I owe you beer

**Comment by dakami** [comment]
you helped me finally check out kdb that voodoo is raaaaaaaaaaaaaad

**Comment by cirosantilli** [comment]
let me know if you get it working on real hardware, my Pi wasn't happy :-( https://stackoverflow.com/questions/4943857/linux-kernel-live-debugging-how-its-done-and-what-tools-are-used/44226360#44226360

**Comment by dakami** [comment]
Ooh!  Ethernet!

http://sysprogs.com/VisualKernel//kgdboe/

**Comment by dakami** [comment]
Wait, what specifically isn't working for you?

**Comment by cirosantilli** [comment]
> However, sometimes when I did next in sys_write GDB just hung and printed this error message several times:

> Ignoring packet error, continuing...
