### ISSUE TITLE
Data overwrite in `pagemap_get_entry`

### ISSUE THREAD

**Issue by AlexanderHaase** [cirosantilli/linux-kernel-module-cheat#125]
https://github.com/cirosantilli/linux-kernel-module-cheat/blob/873737bd1fc6e5ee0378f21e9df1c52e3f61e3fb/userland/common.h#L44

The buffer passed to `::pread` isn't offset by `nread`. Should be `((uint8_t*)&data)+nread)` or similar.

**Comment by cirosantilli** [comment]
Thanks!
