### ISSUE TITLE
build for gem5, aarch64 fails on include of eerno.h

### ISSUE THREAD

**Issue by itamarbon** [cirosantilli/linux-kernel-module-cheat#127]
Hi,
I tried running build for gem5 using aarch64 with:
./build --download-dependencies gem5-buildroot --arch aarch64

Compilation fails on:
CC [M] linux-kernel-module-cheat/out/kernel_modules/aarch64/kernel_modules/params.o
with the error message:
fatal error: errno.h: No such file or directory
which is called from aarch64_dump_regs.h, from dump_regs.c

Thanks

**Comment by cirosantilli** [comment]
Thanks! Let me know if it hit further issues.
