### ISSUE TITLE
I need to make my own lab

### ISSUE THREAD

**Issue by smalinux** [cirosantilli/linux-kernel-module-cheat#133]
Hello,

This is a great massive and complex lab, i need to build my own lab from scratch.
could you please tell me about what essential tools i need to study and any hints.

thanks.

**Comment by cirosantilli** [comment]
Hi smalinux,

The commands  that this repo runs for each build are actually quite simple, if you do a `--dry-run` of your content of interest, you will likely be able to quickly understand every single line  that is being ran.

For Buildroot this also gives the hello world: https://cirosantilli.com/linux-kernel-module-cheat/#buildroot-hello-world

Let me know if something more specific is not clear after trying the above a bit.
