### ISSUE TITLE
./build --download-dependencies qemu-buildroot raising error

### ISSUE THREAD

**Issue by zTehRyaN** [cirosantilli/linux-kernel-module-cheat#137]
![Screenshot from 2020-11-24 22-05-02](https://user-images.githubusercontent.com/18161946/100152192-97b91180-2ea2-11eb-8ee0-1f8a5eef6a64.png)

**Comment by cirosantilli** [comment]
Matteo, thanks for this report, and sorry for this problem. I'm dealing with it at: https://github.com/cirosantilli/linux-kernel-module-cheat/issues/136 Pro tip: always copy paste text from terminal instead of using screenshots :+1:
