### ISSUE TITLE
add -y option to apt-get install commands

### ISSUE THREAD

**Issue by bootrino** [cirosantilli/linux-kernel-module-cheat#14]
This appears to add various packages using the ubuntu apt command.

Suggestion to ad the -y command so no confirmation is needed and they auto install.

thanks

**Comment by cirosantilli** [comment]
This can be achieved currently with `./configure -t` currently, and is used in the (innactive) travis script.

One should never ever do `apt-get install -y`, as for some packages it can end up removing tons of incompatible things from the system and make it not login anymore.

I speak from personal experience :-)
