### ISSUE TITLE
Typo: README.adoc

### ISSUE THREAD

**Issue by smalinux** [cirosantilli/linux-kernel-module-cheat#140]
Hi, I'm sorry I don't know how to I can edit this typo and make a pull request.
Typo 1:
`./gdbserver.sh ./c/print_argv.out asdf qwer`
It should to be:
`./gdbserver.sh ./c/command_line_arguments.out asdf qwer`
Typo 2: 
`./run --gdbserver --userland "$(./getvar userland_build_dir)/c/print_argv.out"`
**I'm not sure** but I think It should to be:
`./run-gdb --gdbserver --userland "$(./getvar userland_build_dir)/c/command_line_arguments.out"`

**Comment by cirosantilli** [comment]
Thanks!
