### ISSUE TITLE
gem5 now build with arm64 command.

### ISSUE THREAD

**Issue by EE415-20170470** [cirosantilli/linux-kernel-module-cheat#145]
![111](https://user-images.githubusercontent.com/56035831/109395746-605e7300-7971-11eb-8caa-ecdd91a278a6.png)

I have error on running `./build --arch aarch64 --download-dependencies gem5-buildroot command because gem5 now build with arm64 command!`

I also has same error on #143 because I think some environment missed when running only `./build-buildroot -- glibc-reconfigure`

**Comment by cirosantilli** [comment]
Can you try:

```
sudo apt install liblua5.4-dev
```

and then check with:

```
./build-m5 -aA
```

? The m5 has an annoying dependency on lua I believe.

**Comment by EE415-20170470** [comment]
I think you can just change 

```
        if self.env['arch'] == 'x86_64':
            env['gem5_m5_source_dir_build_arch'] = 'x86'
        else:
            env['gem5_m5_source_dir_build_arch'] = env['arch']
```

to

```
        if self.env['arch'] == 'x86_64':
            env['gem5_m5_source_dir_build_arch'] = 'x86'
        elif env['host'] == 'aarch64':
            env['gem5_m5_source_dir_build_arch'] = 'arm64'
        else:
            env['gem5_m5_source_dir_build_arch'] = env['arch']
```

in common.py.

It solved my error.

**Comment by cirosantilli** [comment]
Thanks for the patch!!!
