### ISSUE TITLE
Plan to support RISC-V architecture?

### ISSUE THREAD

**Issue by BeenLi** [cirosantilli/linux-kernel-module-cheat#174]

**Comment by cirosantilli** [comment]
Send PR and I'll gladly merge. I have booted RISC-V buildroot on QEMU in the past, so definitely doable, wasn't hard. Try this config: https://github.com/buildroot/buildroot/blob/master/configs/qemu_riscv64_virt_defconfig

**Comment by BeenLi** [comment]
ok, thanks. I'll try it when I have time.

**Comment by cirosantilli** [comment]
Some tips if you try:

- first use this minimal procedure but with the riscv64 config: https://stackoverflow.com/questions/47557262/how-to-download-the-torvalds-linux-kernel-master-recompile-it-and-boot-it-wi/49349237#49349237
- do it on the same version of buildroot as in this repo, currently 2020.08.1 + two minor patches, hopefully we can avoid changing buildroot version as it can break other things unexpectedly
