### ISSUE TITLE
Docker setup fails due to outdated git version: E: Version '1:2.36.0-0ppa1~ubuntu20.04.1' for 'git' was not found

### ISSUE THREAD

**Issue by nukelet** [cirosantilli/linux-kernel-module-cheat#219]
During the Docker host setup, the `setup` script tries to fetch `1:2.36.0-0ppa1~ubuntu20.04.1 `:

```
if [ -f /.dockerenv ]; then
  apt install -y software-properties-common
  add-apt-repository -y ppa:git-core/ppa
  $sudo apt update
  git=git=1:2.36.0-0ppa1~ubuntu20.04.1
```

This causes an error:
```
+ git=git=1:2.36.0-0ppa1~ubuntu20.04.1
+ apt-get install -y git=1:2.36.0-0ppa1~ubuntu20.04.1 python3 python3-pip python3-distutils
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1:2.36.0-0ppa1~ubuntu20.04.1' for 'git' was not found
```

because the latest stable version in the PPA seems to have been recently [updated](https://launchpad.net/~git-core/+archive/ubuntu/ppa) to `1:2.36.1-0ppa1~ubuntu20.04.1`. Changing the git version in the `setup` script fixes the problem.

**Comment by cirosantilli** [comment]
Valeu! I was going to complain that I hat Ubuntu. But the existence of the wildcard method made me change my mind...
