### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by jordankmanier** [cirosantilli/linux-kernel-module-cheat#25]
hey, I have a project im working on and would like to use your gem5 sim. im pretty new to gem5 and build root. I get this error when trying to configure E: You must put some 'source' URIs in your sources.list any help?

**Comment by jordankmanier** [comment]
sorry, I figured it out.

**Comment by cirosantilli** [comment]
Hi Jordan,

Don't worry too much about it, if you have difficulties, google and grep a bit, and then ask away.

For the benefit of further readers, this should solve the problem: https://askubuntu.com/questions/496549/error-you-must-put-some-source-uris-in-your-sources-list/857433#857433

If this is solved, can we close the issue?

**Comment by jordankmanier** [comment]
Thanks a lot, I appreciate your response. 

I have another question. will this tool generate a bootable system to run on gem5 with benchmarks? This is what I'm looking for. 
ive tried attempting to create one in buildroot, but no success. 
thank you for the help!!

**Comment by cirosantilli** [comment]
Yes, it will, and it uses buildroot with carefully chosen confgurations.

You just have to enable the benchmarks you care about e.g. https://github.com/cirosantilli/linux-kernel-module-cheat/tree/7c16eb6ec1c98ac605a9324f37a0d13a8349e756#parsec-benchmark

**Comment by jordankmanier** [comment]
Man this Is amazing! do you have a page where I can donate too? 
you guys are awesome!!
keep up the great work!

**Comment by cirosantilli** [comment]
:-)

I don't have a donation mechanism for now.

Making good bug reports, and telling friends who might be interested in the project is enough ;-)

**Comment by jordankmanier** [comment]
can I add the benchmarks after a build? or does it have to be done with the build?

**Comment by jordankmanier** [comment]
ok nice! 
how would i add the parsec benchmarks to my build?
