### ISSUE TITLE
how to build after adding a C file to kernel_module/user ?

### ISSUE THREAD

**Issue by kamomil** [cirosantilli/linux-kernel-module-cheat#27]
I added a C file to  `kernel_module/user` (after the first build)
then ran  `./build && ./run`
but the corresponding `.out` file is not there,
how do I build to add it ?

**Comment by kamomil** [comment]
ok, I was able with `./build kernel_module-reconfigure`

**Comment by cirosantilli** [comment]
;-)

See also: https://github.com/cirosantilli/linux-kernel-module-cheat/tree/1b0c52784874fa982a4ced5eab137359f34a8b84#rebuild which documents the shortcut `./build -k`.
